### ISSUE TITLE
NoneType Error

### ISSUE THREAD

**Issue by iethan** [marcosschroh/youtube-audio-downloader#1]
I added two links with no empty returns to a txt file and am receiving this:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/sound-down", line 18, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/sound-down", line 14, in main
    downloader.download_audios()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sound_downloader/downloader.py", line 22, in download_audios
    video = pafy.new(link)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pafy/pafy.py", line 125, in new
    return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object is not subscriptable`

**Comment by marcosschroh** [comment]
Hi @iethan ,

Thanks for your feedback. 

I've updated the version. Could you try again?

Best regards,

Marcos.
