### ISSUE TITLE
HTTP not supported when downloading from YouTube

### ISSUE THREAD

**Issue by xavierliwei** [marcosschroh/youtube-audio-downloader#17]
Traceback (most recent call last):
  File "/Users/weili/Library/Python/3.8/bin/sound-down", line 8, in <module>
    sys.exit(main())
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/sound_downloader/scripts/sound_down.py", line 19, in main
    downloader.download_audios()
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/sound_downloader/downloader.py", line 52, in download_audios
    video = pafy.new(link)
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/pafy/pafy.py", line 125, in new
    return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/Users/weili/Library/Python/3.8/lib/python/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: ye4jAQ0uxcQ: Youtube says: HTTP is not supported.

**Comment by cwienands1** [comment]
I found a similar issue reported on another YouTube-related project: https://github.com/mps-youtube/mps-youtube/issues/986

Looks like the `pafy` library is the problem, and the issue is fixed in a later version. I quote:
> For anyone still facing this problem, upgrade your pafy to v0.5.5 or greater with:
`$ pip3 install pafy -U`

Unfortunately this didn't work for me (pip upgraded pafy to 0.5.5). Now I am getting the error message
`OSError: ERROR: 39svBN954-M: Youtube says: Invalid parameters.`
