### ISSUE TITLE
Getting Error on Windows

### ISSUE THREAD

**Issue by romreviewer** [marcosschroh/youtube-audio-downloader#8]
**Describe the bug**
I am Getting This Error

Traceback (most recent call last):
  File "C:\Users\Sanchit\AppData\Local\Programs\Python\Python36-32\Scripts\sound-down-script.py", line 11, in <module>
    load_entry_point('youtube-audio-downloader==1.1.8', 'console_scripts', 'sound-down')()
  File "c:\users\sanchit\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\sanchit\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\users\sanchit\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\users\sanchit\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'sound_downloader.scripts'

**To Reproduce**
By Calling sound-down in cmd

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by marcelobarrosalmeida** [comment]
Almost the same here (module name was different), using Linux (Xubuntu 18.04 64)

Traceback (most recent call last):
  File "/usr/local/bin/sound-down", line 11, in <module>
    load_entry_point('youtube-audio-downloader==1.1.8', 'console_scripts', 'sound-down')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named scripts.sound_down

**Comment by marcosschroh** [comment]
Hi,

@Sanchit43 @marcelobarrosalmeida 

Sorry for the delay. I have fixed the script to `sound-down` but is working only on UNIX. Unfortunately, I have tried on windows several approaches but there is a library that is failing.

Now the version is 1.1.9

Best regards,

Marcos

**Comment by clifftsung** [comment]
Same error, I think you should indicate that this project does not work on Windows platform to save people some time

**Comment by marcosschroh** [comment]
Hi @zjcong, thanks for your feedback. I could not get it for `windows`. Pull request are more than welcome!!
